name: cd
concurrency: cd # 1 release at a time

on:
  workflow_run:
    types: [completed]
    workflows: [ci]
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # install binaries
      - uses: extractions/setup-just@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"
      - uses: snok/install-poetry@v1

      # setup jfrog
      - name: authn with jfrog
        run: poetry config http-basic.steadily github ${{ secrets.JFROG_GITHUB_PASSWORD }}

      # run
      - uses: actions/checkout@v2

      - name: version
        id: version
        run: |
          poetry version patch
          echo '::set-output name=VERSION::'$(poetry version -s)

      - name: commit version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Publish Version v${{ steps.version.outputs.VERSION }}
          tagging_message: v${{ steps.version.outputs.VERSION }}

      - name: publish
        run: just publish
